#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd with username,
# user ID, and home directory path for each user.

while IFS=':' read -r username _ uid _ _ home_dir _; do
    echo "$username:$uid:$home_dir"
done < /etc/passwd
