#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

HOURS=0
while (( HOURS < 13 )); do
    echo "Hour: $HOURS"
    MINUTES=1
    while (( MINUTES < 60 )); do
        echo $MINUTES
        (( MINUTES += 1 ))
    done
    (( HOURS += 1 ))
done

