#!/usr/bin/env bash

# Check for sudo privileges
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo."
    exit 1
fi

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Update the hosts file
    echo "127.0.0.2	localhost" > /etc/hosts
    echo "8.8.8.8	facebook.com" >> /etc/hosts

    echo "Hosts file updated successfully."

