#!/bin/bash

# Use ifconfig to get the active IPv4 addresses and filter out the loopback address
ipv4_addresses=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*)' | awk '{print $2}' | grep -v '127.0.0.1')

# Print the active IPv4 addresses
echo "$ipv4_addresses"

